video_exts:
  - ".mkv"
  - ".mp4"
  - ".mov"
  - ".avi"
  - ".wmv"
  - ".flv"
  - ".webm"
  - ".m4v"
  - ".3gp"
  - ".ts"
  - ".m2ts"

audio_exts:
  - ".mp3"
  - ".flac"
  - ".aac"
  - ".ogg"
  - ".opus"
  - ".wav"
  - ".m4a"
  - ".wma"

image_exts:
  - ".jpg"
  - ".jpeg"
  - ".png"
  - ".gif"
  - ".bmp"
  - ".webp"
  - ".tiff"
  - ".svg"

doc_exts:
  - ".pdf"
  - ".txt"
  - ".doc"
  - ".docx"
  - ".ppt"
  - ".pptx"
  - ".ppt"
  - ".pptx"
  - ".md"
